# -*- coding: utf-8 -*-
"""how2doMiF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eec_ojd0OoqPE5ze906eI9rfXr23g6t_
"""

!pip install git+https://hilolani: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@github.com/hilolani/mif.git

from mif import *

mif = load_mif()

print(mif)

print(mif.gadget)
print(mif.karateclub)
print(mif.erdosReny)
print(mif.scalefree)
print(mif.homophilly)
print(mif.heterophilly)

mtxlist = [mif.gadget,mif.karateclub,mif.erdosReny,mif.scalefree,mif.homophilly,mif.heterophilly]
[adjanceyinfocheck(i) for i in mtxlist]

adjacencylist = ['gadget', 'karateclub', 'erdosReny', 'scalefree', 'homophilly', 'heterophilly']

for i in range(0,len(mtxlist)):
    print("")
    print(f"MiF example for {adjacencylist[i]}")
    print("")
    log = MiF(mtxlist[i], 4, 32, 0.5, 3)
    print(log)
    print("...")
    del log
print("")

for i in range(0,len(mtxlist)):
    print("")
    print(f"MiFbroadcast example for {adjacencylist[i]}")
    print("")
    log = MiF_broadcast(mtxlist[i], 3)
    print("...")
    del log
print("")

for i in range(0,len(mtxlist)):
    print("")
    print(f"MiFbroadcast example for {adjacencylist[i]}")
    print("")
    log = MiF_broadcast(mtxlist[i], 3, loop = 1)
    print("...")
    del log
print("")


for i in range(0,len(mtxlist)):
    print("")
    print(f"MiFDI for {adjacencylist[i]}")
    print("")
    log = MiFDI(mtxlist[i])
    print("...")
    del log
print("")

for i in range(0,len(mtxlist)):
    print("")
    print(f"MiFDI for {adjacencylist[i]}")
    print("")
    log = MiFDI(mtxlist[i], startingvertices="max")
    print("...")
    del log
print("")

for i in range(0,len(mtxlist)):
    print("")
    print(f"MiFDI for {adjacencylist[i]}")
    print("")
    log = MiFDI(mtxlist[i], loop = 1)
    print("...")
    del log
print("")

for i in range(0,len(mtxlist)):
    print("")
    print(f"MiFDI for {adjacencylist[i]}")
    print("")
    log = MiFDI(mtxlist[i], startingvertices="max", loop =1)
    print("...")
    del log

