# -*- coding: utf-8 -*-
"""How2doMiF_ver20251202.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXz-5U7V9CpVe9okw4nln2X5Y_orjj6c
"""

!pip install git+https://github.com/hilolani/mif.git

from mif import *
mif = load_mif()
print(mif)
mtxlist = [mif.gadget,mif.karateclub,mif.erdosReny,mif.scalefree,mif.homophilly,mif.heterophilly]
adjacencylist = [adjacencyinfocheck(i) for i in mtxlist]

#Gadget
#MiF value between the vertices 4 and 32 under the default settings.
i = 0
log_mif0 = MiF(adjacencylist[i], 4, 32, 0.5, 3)
print(log_mif0)

#Karate club
#MiF value between the vertices 4 and 32 under the default settings.
i = 1
log_mif1 = MiF(adjacencylist[i], 4, 32, 0.5, 3)
print(log_mif1)

#erdosReny
#MiF value between the vertices 4 and 32 under the default settings.
i = 2
log_mif2 = MiF(adjacencylist[i], 4, 32, 0.5, 3)
print(log_mif2)

#scalefree
#MiF value between the vertices 4 and 32 under the default settings.
i = 3
log_mif3 = MiF(adjacencylist[i], 4, 32, 0.5, 3)
print(log_mif3)

#homophilly
#MiF value between the vertices 4 and 32 under the default settings.
i = 4
log_mif4 = MiF(adjacencylist[i], 4, 32, 0.5, 3)
print(log_mif4)

#heterophilly
#MiF value between the vertices 4 and 32 under the default settings.
i = 5
log_mif5 = MiF(adjacencylist[i], 4, 32, 0.5, 3)
print(log_mif5)

#Gadget network setting the vertex 3 as the starting node.
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
i = 0
log_without0 = MiF_broadcast(adjacencylist[i], 3)
log_with0 = MiF_broadcast(adjacencylist[i], 3, loop = 1)
print(f"MiF brodacast without loop: {log_without0}")
print(f"MiF brodacast with loop: {log_with0}")

#The pairwise comparison (difference) between the two broadcast outcomes (with or without self-loop) is checked by the function of MiF_broadcast_diff_on_loop.
MiF_broadcast_diff_on_loop(log_with0, log_without0)

#Karate club setting the vertex 3 as the starting node.
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
i = 1
log_without1 = MiF_broadcast(adjacencylist[i], 3)
log_with1 = MiF_broadcast(adjacencylist[i], 3, loop = 1)
print(f"MiF brodacast without loop: {log_without1}")
print(f"MiF brodacast with loop: {log_with1}")

#Erdos Reny network setting the vertex 3 as the starting node.
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
i = 2
log_without2 = MiF_broadcast(adjacencylist[i], 3)
log_with2 = MiF_broadcast(adjacencylist[i], 3, loop = 1)
print(f"MiF brodacast without loop: {log_without2}")
print(f"MiF brodacast with loop: {log_with2}")

#Scale Free network setting the vertex 3 as the starting node.
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
i = 3
log_without3 = MiF_broadcast(adjacencylist[i], 3)
log_with3 = MiF_broadcast(adjacencylist[i], 3, loop = 1)
print(f"MiF brodacast without loop: {log_without3}")
print(f"MiF brodacast with loop: {log_with3}")

#homophilly network setting the vertex 3 as the starting node.
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
i = 4
log_without4 = MiF_broadcast(adjacencylist[i], 3)
log_with4 = MiF_broadcast(adjacencylist[i], 3, loop = 1)
print(f"MiF brodacast without loop: {log_without4}")
print(f"MiF brodacast with loop: {log_with4}")

#heterophilly network setting the vertex 3 as the starting node.
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
i = 5
log_without5 = MiF_broadcast(adjacencylist[i], 3)
log_with5 = MiF_broadcast(adjacencylist[i], 3, loop = 1)
print(f"MiF brodacast without loop: {log_without5}")
print(f"MiF brodacast with loop: {log_with5}")

#MiFDI information for Gadget network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the smallest.
#Result is displayed for the first node having the smallest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1.
i = 0
logdiwithout0, logdiwithoutmifdival0 = MiFDI(adjacencylist[i], dangn = 0)
logdiwith0, logdiwithmifdival0 = MiFDI(adjacencylist[i], dangn = 0, loop = 1)
print(f"MiFDI result without loop: {logdiwithout0}")
print(f"MiF values without loop: {logdiwithoutmifdival0}")
print(f"MiFDI result with loop: {logdiwith0}")
print(f"MiF values with loop: {logdiwithmifdival0}")

#MiFDI information for Karate Club network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the smallest.
#Result is displayed for the first node having the smallest degree (dagn = 0). If you want to get the information related to ths second node, set dagn = 1.
i = 1
logdiwithout1, logdiwithoutmifdival1 = MiFDI(adjacencylist[i], dangn = 0)
logdiwith1, logdiwithmifdival1 = MiFDI(adjacencylist[i], dangn = 0, loop = 1)
print(f"MiFDI result without loop: {logdiwithout1}")
print(f"MiF values without loop: {logdiwithoutmifdival1}")
print(f"MiFDI result with loop: {logdiwith1}")
print(f"MiF values with loop: {logdiwithmifdival1}")

#MiFDI information for Erdos Reny network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the smallest.
#Result is displayed for the first node having the smallest degree (dagn = 0). If you want to get the information related to ths second node, set dagn = 1.
i = 2
logdiwithout2, logdiwithoutmifdival2 = MiFDI(adjacencylist[i], dangn = 0)
logdiwith2, logdiwithmifdival2 = MiFDI(adjacencylist[i], dangn = 0, loop = 1)
print(f"MiFDI result without loop: {logdiwithout2}")
print(f"MiF values without loop: {logdiwithoutmifdival2}")
print(f"MiFDI result with loop: {logdiwith2}")
print(f"MiF values with loop: {logdiwithmifdival2}")

#MiFDI information for Scalefree network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the smallest.
#Result is displayed for the first node having the smallest degree (dagn = 0). If you want to get the information related to ths second node, set dagn = 1.
i = 3
logdiwithout3, logdiwithoutmifdival3 = MiFDI(adjacencylist[i], dangn = 0)
logdiwith3, logdiwithmifdival3 = MiFDI(adjacencylist[i], dangn = 0, loop = 1)
print(f"MiFDI result without loop: {logdiwithout3}")
print(f"MiF values without loop: {logdiwithoutmifdival3}")
print(f"MiFDI result with loop: {logdiwith3}")
print(f"MiF values with loop: {logdiwithmifdival3}")

#MiFDI information for homophilly network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the smallest.
#Result is displayed for the first node having the smallest degree (dagn = 0). If you want to get the information related to ths second node, set dagn = 1.
i = 4
logdiwithout4, logdiwithoutmifdival4 = MiFDI(adjacencylist[i], dangn = 0)
logdiwith4, logdiwithmifdival4 = MiFDI(adjacencylist[i], dangn = 0, loop = 1)
print(f"MiFDI result without loop: {logdiwithout4}")
print(f"MiF values without loop: {logdiwithoutmifdival4}")
print(f"MiFDI result with loop: {logdiwith4}")
print(f"MiF values with loop: {logdiwithmifdival4}")

#MiFDI information for heterophilly network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the smallest.
#Result is displayed for the first node having the smallest degree (dagn = 0). If you want to get the information related to ths second node, set dagn = 1.
i = 5
logdiwithout5, logdiwithoutmifdival5 = MiFDI(adjacencylist[i], dangn = 0)
logdiwith5, logdiwithmifdival5 = MiFDI(adjacencylist[i], dangn = 0, loop = 1)
print(f"MiFDI result without loop: {logdiwithout5}")
print(f"MiF values without loop: {logdiwithoutmifdival5}")
print(f"MiFDI result with loop: {logdiwith5}")
print(f"MiF values with loop: {logdiwithmifdival5}")

#MiFDI information for Gadget network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the largest.
#Result is displayed for the first node having the largest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1 (if there is the second node).
i = 0
logdimaxwithout0, logdimaxwithoutmifdival0 = MiFDI(adjacencylist[i], startingvertices="max",  dangn = 0)
logdimaxwith0, logdimaxwithmifdival0 = MiFDI(adjacencylist[i], startingvertices="max", dangn = 0, loop = 1)
print(f"MiFDI result without loop starting from a hub node: {logdimaxwithout0}")
print(f"MiF values without loop from a hub node: {logdimaxwithoutmifdival0}")
print(f"MiFDI result with loop from a hub node: {logdimaxwith0}")
print(f"MiF values with loop from a hub node: {logdimaxwithmifdival0}")

#MiFDI information for Karate Club network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the largest.
#Result is displayed for the first node having the largest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1 (if there is the second node).
i = 1
logdimaxwithout1, logdimaxwithoutmifdival1 = MiFDI(adjacencylist[i], startingvertices="max",  dangn = 0)
logdimaxwith1, logdimaxwithmifdival1 = MiFDI(adjacencylist[i], startingvertices="max", dangn = 0, loop = 1)
print(f"MiFDI result without loop starting from a hub node: {logdimaxwithout1}")
print(f"MiF values without loop from a hub node: {logdimaxwithoutmifdival1}")
print(f"MiFDI result with loop from a hub node: {logdimaxwith1}")
print(f"MiF values with loop from a hub node: {logdimaxwithmifdival1}")

#MiFDI information for Erdos Reny network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the largest.
#Result is displayed for the first node having the largest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1 (if there is the second node).
i = 2
logdimaxwithout2, logdimaxwithoutmifdival2 = MiFDI(adjacencylist[i], startingvertices="max",  dangn = 0)
logdimaxwith2, logdimaxwithmifdival2 = MiFDI(adjacencylist[i], startingvertices="max", dangn = 0, loop = 1)
print(f"MiFDI result without loop starting from a hub node: {logdimaxwithout2}")
print(f"MiF values without loop from a hub node: {logdimaxwithoutmifdival2}")
print(f"MiFDI result with loop from a hub node: {logdimaxwith2}")
print(f"MiF values with loop from a hub node: {logdimaxwithmifdival2}")

#MiFDI information for Scale free network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the largest.
#Result is displayed for the first node having the largest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1 (if there is the second node).
i = 3
logdimaxwithout3, logdimaxwithoutmifdival3 = MiFDI(adjacencylist[i], startingvertices="max",  dangn = 0)
logdimaxwith3, logdimaxwithmifdival3 = MiFDI(adjacencylist[i], startingvertices="max", dangn = 0, loop = 1)
print(f"MiFDI result without loop starting from a hub node: {logdimaxwithout3}")
print(f"MiF values without loop from a hub node: {logdimaxwithoutmifdival3}")
print(f"MiFDI result with loop from a hub node: {logdimaxwith3}")
print(f"MiF values with loop from a hub node: {logdimaxwithmifdival3}")

#MiFDI information for homophilly network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the largest.
#Result is displayed for the first node having the largest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1 (if there is the second node).
i = 4
logdimaxwithout4, logdimaxwithoutmifdival4 = MiFDI(adjacencylist[i], startingvertices="max",  dangn = 0)
logdimaxwith4, logdimaxwithmifdival4 = MiFDI(adjacencylist[i], startingvertices="max", dangn = 0, loop = 1)
print(f"MiFDI result without loop starting from a hub node: {logdimaxwithout4}")
print(f"MiF values without loop from a hub node: {logdimaxwithoutmifdival4}")
print(f"MiFDI result with loop from a hub node: {logdimaxwith4}")
print(f"MiF values with loop from a hub node: {logdimaxwithmifdival4}")

#MiFDI information for heterophilly network
#The default condition of loop = 0 doesn't allow the random walker to loop back to the same node.
#If loop = 1, there is no such constraint.
#All the starting nodes are chosen under the condition that their degrees are the largest.
#Result is displayed for the first node having the largest degree (dagn =0). If you want to get the information related to ths second node, set dagn = 1 (if there is the second node).
i = 5
logdimaxwithout5, logdimaxwithoutmifdival5 = MiFDI(adjacencylist[i], startingvertices="max",  dangn = 0)
logdimaxwith5, logdimaxwithmifdival5 = MiFDI(adjacencylist[i], startingvertices="max", dangn = 0, loop = 1)
print(f"MiFDI result without loop starting from a hub node: {logdimaxwithout5}")
print(f"MiF values without loop from a hub node: {logdimaxwithoutmifdival5}")
print(f"MiFDI result with loop from a hub node: {logdimaxwith5}")
print(f"MiF values with loop from a hub node: {logdimaxwithmifdival5}")

#The pairwise comparison (difference) between the two MiFDI outcomes (with or without self-loop) is checked by the function of MiFDI_diff_on_loop.
MiFDI_diff_on_loop(logdimaxwith5, logdimaxwithout5)

#If you wish to return MiFDI information from all starting points collectively,
#set the value of the sixth argument "allstartinginfo" of the MiFDI() to 1 by adding "allstartinginfo = 1" when executing this function.
i = 0
logdiallwithout0, logdiallwithoutmifdival0 = MiFDI(adjacencylist[i], dangn = 0, allstartinginfo = 1)
logdiallwith0, logdiallwithmifdival0 = MiFDI(adjacencylist[i], dangn = 0, allstartinginfo = 1, loop = 1)
print(f"MiFDI result without loop: {logdiallwithout0}")
print(f"MiF values without loop: {logdiallwithoutmifdival0}")
print(f"MiFDI result with loop: {logdiallwith0}")
print(f"MiF values with loop: {logdiallwithmifdival0}")

print(len(logdiallwithout0))
print(len(logdiallwithoutmifdival0))
print(len(logdiallwith0))
print(len(logdiallwithmifdival0))
print("......")
print(len(logdiallwithout0[0]))
print(len(logdiallwithoutmifdival0[0]))
print(len(logdiallwith0[0]))
print(len(logdiallwithmifdival0[0]))

